version: '3.8'

services:
  # Servicio de la aplicación Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    container_name: ecom-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - app_vendor:/var/www/vendor
    networks:
      - ecom_network

  # Servidor Web Nginx
  nginx:
    image: nginx:1.21-alpine
    container_name: ecom-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - ecom_network

  # Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: ecom-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ecom_network

  # Servidor de Caché Redis
  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    restart: unless-stopped
    ports:
      - "63790:6379"
    networks:
      - ecom_network

networks:
  ecom_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  app_vendor: {}